### ISSUE TITLE
A-z keys

### ISSUE THREAD

**Issue by raat1979** [gvdhoven/neeo-driver-ziggo-horizon#2]
Any chance you could, add the "standard/ascii" buttons (a-z) as defined in the vnc/rfb specs
See also https://vncdotool.readthedocs.io/en/0.8.0/rfbproto.html#keyevent

**Comment by gvdhoven** [comment]
Feel free to add it and submit a PR for it@raat1979 ; i no longer maintain this code since i don't actively use it.
